# NextGCore AMF Configuration
# PLMN 999-70, TAC 1, S-NSSAI SST=1

amf:
  amf_name: "NextGCore AMF"

  guami:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      amf_id:
        region: 1
        set: 1
        pointer: 1

  tai:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      tac: 1

  plmn_support:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      s_nssai:
        - sst: 1

  security:
    integrity_order: ["NIA2", "NIA1", "NIA0"]
    ciphering_order: ["NEA2", "NEA1", "NEA0"]
