# PCF (Policy Control Function) Configuration
# Docker container configuration for 5G Core deployment

db_uri: mongodb://172.23.0.2/nextgcore

logger:
  file:
    path: /var/log/nextgcore/pcf.log
  level: info

global:
  max:
    ue: 1024
    peer: 64

pcf:
  sbi:
    server:
      - address: 172.23.0.13
        port: 7777
    client:
      nrf:
        - uri: http://172.23.0.10:7777
  metrics:
    server:
      - address: 172.23.0.13
        port: 9090
